app/home/forms.py
# app/home/forms.py

import pdb

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.ext.dateutil.fields import DateTimeField
from ..models import Coin, CoinApi, CoinPrice, Wallet, User
from app import db

class UserWalletForm(FlaskForm):
    """
    Form for admin to add or edit a wallet
    """
    address = StringField('Address', validators=[DataRequired()])
    coin = QuerySelectField(query_factory=lambda: Coin.query.all(), get_label="name")
    submit = SubmitField('Submit')
    
class AccountInfoForm(FlaskForm):
    """
    Form for user to edit their account info
    """
    email = StringField('Email', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py
import pdb

import datetime

from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import home
from forms import UserWalletForm, AccountInfoForm
from .. import db
from ..models import User, Wallet, Balance
from tasks import get_coin_prices, get_latest_coin_price, get_coin_qty

def check_user(user_id):
    """
    Prevent users from accessing another user
    """
    if not current_user.id == user_id:
        abort(403)

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    get_coin_prices(start_time=datetime.datetime.now())

    wallets = User.query.get_or_404(current_user.id).wallets

    balances = []
    total_value = 0.00

    if wallets:
        for wallet in wallets:
            price, date = get_latest_coin_price(wallet.Coin.symbol)
            qty_coins = get_coin_qty(wallet)
            price = float("%.2f" % price)

            if type(qty_coins) is unicode:
                balance = Balance(coin_symbol = wallet.Coin.symbol,
                              coin_price = price,
                              coin_price_date = date,
                              address = wallet.address,
                              num_coins = qty_coins,
                              usd_value = 'n/a')
                balances.append(balance)

            else:
                balance = Balance(coin_symbol = wallet.Coin.symbol,
                                  coin_price = price,
                                  coin_price_date = date,
                                  address = wallet.address,
                                  num_coins = qty_coins,
                                  usd_value = "%.2f" % (price * qty_coins))
                balances.append(balance)
                total_value += price*qty_coins

    return render_template('home/dashboard.html', balances=balances, total_value="%.2f" % (total_value), title="Dashboard")


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)
    try:

        get_coin_prices(start_time=datetime.datetime.now())

        wallets = User.query.get_or_404(current_user.id).wallets

        balances = []
        total_value = 0.00

        if wallets:
            for wallet in wallets:
                price, date = get_latest_coin_price(wallet.Coin.symbol)
                qty_coins = get_coin_qty(wallet)
                price = float("%.2f" % price)

                if type(qty_coins) is unicode:
                    balance = Balance(coin_symbol = wallet.Coin.symbol,
                                  coin_price = price,
                                  coin_price_date = date,
                                  address = wallet.address,
                                  num_coins = qty_coins,
                                  usd_value = 'n/a')
                    balances.append(balance)

                else:
                    balance = Balance(coin_symbol = wallet.Coin.symbol,
                                      coin_price = price,
                                      coin_price_date = date,
                                      address = wallet.address,
                                      num_coins = qty_coins,
                                      usd_value = "%.2f" % (price * qty_coins))
                    balances.append(balance)
                    total_value += price*qty_coins

        return render_template('home/admin_dashboard.html', balances=balances, total_value="%.2f" % (total_value), title="Dashboard")

    except Exception as e:
        error_message = 'Error getting coin prices from API.  The coin price API may be down.  Error Message: ' + str(e.message)
        flash(error_message)
        return render_template('home/admin_dashboard.html', error=error_message, title="Dashboard")

##################
# Account Info Views
##################
@home.route('/account_info')
@login_required
def list_account_info():
    """
    List user
    """
    check_user(current_user.id)

    user = User.query.get_or_404(current_user.id)
    wallets = User.query.get_or_404(current_user.id).wallets
    return render_template('home/account_info/account_info.html',
                           user=user, wallets=wallets, title='Account Info')

@home.route('/account_info/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_account_info(id):
    """
    Edit user
    """
    check_user(id)

    add_user = False

    user = User.query.get_or_404(id)
    form = AccountInfoForm(obj=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        db.session.add(user)
        db.session.commit()
        flash('You have successfully edited your user account.')

        # redirect to the users page
        return redirect(url_for('home.list_account_info'))

    form.email.data = user.email
    form.username.data = user.username
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    return render_template('home/account_info/edit_account_info.html', edit_account_info=edit_account_info,
                           form=form, title="Edit Account Info")

######################
# User Wallet Views
######################
@home.route('/user_wallet/add', methods=['GET', 'POST'])
@login_required
def add_user_wallet():
    """
    Add a wallet for the user to the database
    """

    check_user(current_user.id)

    add_user_wallet = True

    user = current_user

    form = UserWalletForm()
    if form.validate_on_submit():
        wallet = Wallet(address=form.address.data,
                    User= user,
                    Coin=form.coin.data)

        try:
            # add user's wallet to the database
            db.session.add(wallet)
            db.session.commit()
            flash('You have successfully added a new wallet.')
        except:
            # in case wallet name already exists
            flash('Error: Wallet address already exists.')

        # redirect to the wallets page
        return redirect(url_for('home.list_account_info'))

    # load wallet template
    return render_template('home/user_wallets/add_user_wallet.html', add_user_wallet=add_user_wallet,
                           form=form, title='Add Wallet')


@home.route('/user_wallets/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_user_wallet(id):
    """
    Edit a user wallet
    """
    add_user_wallet = False

    wallet = Wallet.query.get_or_404(id)

    check_user(wallet.user_id)

    user = User.query.get_or_404(id)
    form = UserWalletForm(obj=wallet)
    if form.validate_on_submit():
        wallet.address = form.address.data
        wallet.Coin = form.coin.data
        wallet.User = user
        db.session.add(wallet)
        db.session.commit()
        flash('You have successfully edited the wallet.')

        # redirect to the wallets page
        return redirect(url_for('home.list_account_info'))

    form.address.data = wallet.address
    form.user.data = wallet.User
    form.coin.data = wallet.Coin
    return render_template('home/user_wallets/add_user_wallet.html', add_user_wallet=add_user_wallet,
                           form=form, title="Edit Wallet")

@home.route('/user_wallets/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_user_wallet(id):
    """
    Delete a user's wallet from the database
    """
    wallet = Wallet.query.get_or_404(id)

    check_user(wallet.user_id)

    db.session.delete(wallet)
    db.session.commit()
    flash('You have successfully deleted the wallet.')

    # redirect to the wallets page
    return redirect(url_for('home.list_account_info'))

    return render_template(title="Delete Wallet")

app/templates/home/account_info/account_info.html
<!-- app/templates/home/account_info/edit_account_info.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Account Info{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
            <br/>
                {{ utils.flashed_messages() }}
            <br/>
            <h1 style="text-align:center;">Account Info</h1>
            {% if user %}
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th width="15%"> Email </th>
                                <th width="10%"> username </th>
                                <th width="20%"> First Name </th>
                                <th width="20%"> Last Name </th>
                                <th width="20%"> Number of Wallets</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td> {{ user.email }} </td>
                                <td> {{ user.username }} </td>
                                <td> {{ user.first_name }} </td>
                                <td> {{ user.last_name }} </td>
                                <td> 
                                    {% if user.wallets %}
                                        {{ user.count_wallets() }} 
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
            {% else %}
                <div style="text-align: center">
                    <h3> Invalid account info information in database. </h3>
                <hr class="intro-divider">
            {% endif %}
                    <a href="{{ url_for('home.edit_account_info',id=user.id) }}" class="btn btn-default btn-lg">
                        <i class="fa fa-plus"></i>
                            Edit Account Info
                    </a>
                </div>
            
            {% if wallets %}
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th width="15%"> Address </th>
                                <th width="20%"> Coin </th>
                                <th width="10%"> Edit </th>
                                <th width="10%"> Delete </th>
                            </tr>
                        </thead>
                        {% for wallet in wallets %}
                            <tr>
                                <td> {{ wallet.address }} </td>
                                <td>
                                    {% if wallet.Coin %}
                                        {{ wallet.Coin.name }}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ url_for('home.edit_user_wallet', id=wallet.id) }}">
                                        <i class="fa fa-pencil"></i> Edit 
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ url_for('home.delete_user_wallet', id=wallet.id) }}">
                                        <i class="fa fa-trash"></i> Delete 
                                    </a>
                                </td>
                            </tr>
                          {% endfor %}
                    </table>
                </div>
                <div style="text-align: center">
            {% else %}
                <div style="text-align: center">
                    <h3> Invalid wallet information in database. </h3>
                <hr class="intro-divider">
            {% endif %}
                    <a href="{{ url_for('home.add_user_wallet', id=user.id) }}" class="btn btn-default btn-lg">
                        <i class="fa fa-plus"></i>
                            Add Wallet
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/account_info/edit_account_info.html
<!-- app/templates/home/account_inf/account_info.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    Edit Account Info
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            <h1>Edit Account Info</h1>
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}